### PR TITLE
Added support to run kibana

### PR DESCRIPTION
**Pull request by lnguyen**

### CODE REVIEW

**Comment by drnic** [comment]
@frodenas yes technically a user can't immediately see kibana via docker services; but we're working on that separately

**Comment by frodenas** [comment]
Thanks!

**Comment by lnguyen** [comment]
can you build and push this as new 1.4? or do we want new tag?

**Comment by frodenas** [comment]
It's built automatically on every push. Take a look at https://registry.hub.docker.com/u/frodenas/logstash/builds_history/38547/.

**Comment by frodenas** [comment]
Sorry, it'll be built on master. I'll merge the 1.4 branch right now.

**Comment by lnguyen** [comment]
oh awesome! thanks!

**Pull request merged**
